-- Migration : nettoyage des colonnes camelCase dupliquées
-- Ces colonnes avaient été ajoutées par erreur par migration_add_missing_columns.sql
-- Le schéma canonique utilise snake_case (schema.sql) — à exécuter dans Supabase → SQL Editor

ALTER TABLE reports
  DROP COLUMN IF EXISTS "tiersType",
  DROP COLUMN IF EXISTS "tiersNom",
  DROP COLUMN IF EXISTS "tiersContact",
  DROP COLUMN IF EXISTS "tiersAssurance",
  DROP COLUMN IF EXISTS "demandeurType",
  DROP COLUMN IF EXISTS "demandeurNom",
  DROP COLUMN IF EXISTS "demandeurContact",
  DROP COLUMN IF EXISTS "dateFirstManif",
  DROP COLUMN IF EXISTS "interventionsAnterieures",
  DROP COLUMN IF EXISTS "surfaceAffectee",
  DROP COLUMN IF EXISTS "signesAlerte",
  DROP COLUMN IF EXISTS "alimentationECS",
  DROP COLUMN IF EXISTS "alimentationECSType",
  DROP COLUMN IF EXISTS "alimentationChauffage",
  DROP COLUMN IF EXISTS "alimentationChauffageType",
  DROP COLUMN IF EXISTS "alimentationEvacuations",
  DROP COLUMN IF EXISTS "alimentationEvacuationsNotes",
  DROP COLUMN IF EXISTS "alimentationIsolation",
  DROP COLUMN IF EXISTS "riskResiduel",
  DROP COLUMN IF EXISTS "responsabiliteExecution";

-- Vérifier que toutes les colonnes snake_case sont bien présentes (schema.sql les crée déjà)
ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS client_civilite text DEFAULT '',
  ADD COLUMN IF NOT EXISTS client_nom text DEFAULT '',
  ADD COLUMN IF NOT EXISTS client_prenom text DEFAULT '',
  ADD COLUMN IF NOT EXISTS client_phone text DEFAULT '',
  ADD COLUMN IF NOT EXISTS client_email text DEFAULT '',
  ADD COLUMN IF NOT EXISTS intervention_address text DEFAULT '',
  ADD COLUMN IF NOT EXISTS problem_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiers_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiers_nom text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiers_contact text DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiers_assurance text DEFAULT '',
  ADD COLUMN IF NOT EXISTS demandeur_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS demandeur_nom text DEFAULT '',
  ADD COLUMN IF NOT EXISTS demandeur_contact text DEFAULT '',
  ADD COLUMN IF NOT EXISTS date_first_manif text DEFAULT '',
  ADD COLUMN IF NOT EXISTS interventions_anterieures text DEFAULT '',
  ADD COLUMN IF NOT EXISTS surface_affectee text DEFAULT '',
  ADD COLUMN IF NOT EXISTS signes_alerte text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_config text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_composition text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_points_acces text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_notes text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_ecs text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_ecs_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_chauffage text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_chauffage_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_evacuations text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_evacuations_notes text DEFAULT '',
  ADD COLUMN IF NOT EXISTS alimentation_isolation text DEFAULT '',
  ADD COLUMN IF NOT EXISTS risk_residuel text DEFAULT '',
  ADD COLUMN IF NOT EXISTS responsabilite_execution text DEFAULT '',
  ADD COLUMN IF NOT EXISTS section_photos jsonb DEFAULT '{}'::jsonb;
